name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install docker
        run: 
      - name: Build Docker image
        run: |
          docker build -t my-image -f path/to/Dockerfile .
      - name: Run Docker container
        run: |
          docker run -d --name my-container my-image
      - name: Run Docker Compose
        run: |
          echo "URL=http://localhost:3000" >> $GITHUB_ENV
          docker-compose up -d
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://localhost:3000'