name: Docker Compose Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: |
          docker-compose -f .github/workflows/docker-compose.yml up -d

  webserver:
    runs-on: ubuntu-latest
    steps:
      - name: Start Nginx container
        run: |
          docker run -d --name webserver -p 3000:3000 -v ${PWD}:/usr/share/nginx/html nginx:alpine
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://localhost:3000'