name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Strating Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: run npm audit
        run: npm audit --audit-level=critical
      # - name: build react-pizza
      #   run: npm run build
      # - name: build storybook
      #   run: npm run build:storybook
      # - name: unit test
      #   run: npm run test:unit
      # - name: e2e test
      #   run: npm run test:e2e
      # - name: lint code
      #   run: npm run lint
      - name: Secret scan
        uses: joocer/fides@main
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.com/arrtmy/react-pizza-1:latest 
      - name: Run Docker Compose
        run: |
          echo "URL=http://localhost:3000" >> $GITHUB_ENV  # Замените на нужный URL
          docker-compose up -d
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'http://localhost:3000'