name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Strating Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --legacy-peer-deps
      - name: build react-pizza
        run: npm run build
      - name: build storybook
        run: npm run build:storybook
      - name: unit test
        run: npm run test:unit
      - name: e2e test
        run: npm run test:e2e
      - name: lint code
        run: npm run lint
      - name: Detect Secret Scanner
        uses: kmnpat/detect-secrets-selfhosted@1.4.0
      - name: SAST Scan 3
        id: salus_scan
        uses: federacy/scan-action@0.1.5
        with:
          active_scanners: "\n  - npm audit"
      - name: SAST scan 2
        uses: Bastion-Technologies/gh-action-run-sast@v1
      # - name: DAST scan
      #   uses: PortSwigger/dastardly-github-action@main
      #   with:
      #     target-url: 'https://zesty-pithivier-c05109.netlify.app/'
        

