name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Strating Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --legacy-peer-deps
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
      - name: audit fix
        run: npm audit fix
      - name: build react-pizza
        run: npm run build
      - name: build storybook
        run: npm run build:storybook
      - name: unit test
        run: npm run test:unit
      - name: e2e test
        run: npm run test:e2e
      - name: lint code
        run: npm run lint
      - name: Secret scan
        uses: joocer/fides@main
      - name: Run Dastardly Action Step
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'

