name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
      - name: Strating Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install --legacy-peer-deps
      - name: build react-pizza
        run: npm run build
      - name: build storybook
        run: npm run build:storybook
      - name: unit test
        run: npm run test:unit
      - name: e2e test
        run: npm run test:e2e
      - name: lint code
        run: npm run lint
